apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - airflow-application.yaml

configMapGenerator:
  - name: airflow-values
    files:
      - airflow-values.yaml

generatorOptions:
  disableNameSuffixHash: true 